import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header`'
import StyledComponentsRegistry from '@/lib/AntdRegistry`'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Header />
      <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
    </html>
  )
}
